apiVersion: v1
kind: Service
metadata:
  name: express-api-svc
spec:
  selector:
    name: express-api
  ports:
    - port: 3000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: express-api
  template:
    metadata:
      labels:
        name: express-api
    spec:
      containers:
      - name: express-api
        image: express-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: postgresql-connection-string
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-url
        - name: REDIS_API_URL
          valueFrom:
            configMapKeyRef:
              name: flask-api-config
              key: flask-api-url                         
        resources:
          requests:
            memory: "256Mi"  # Adjust based on your app-config settings
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"