apiVersion: v1
kind: Service
metadata:
  name: flask-api-svc
spec:
  selector:
    name: flask-api
  ports:
    - port: 8000
      targetPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flask-api
  template:
    metadata:
      labels:
        name: flask-api
    spec:
      containers:
      - name: flask-api
        image: flask-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-port              
        resources:
          requests:
            memory: "256Mi"  # Adjust based on your app-config settings
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
